//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.tsu.famc.ds.SETI.Scout.Proxy {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Target", Namespace="http://schemas.datacontract.org/2004/07/org.tsu.famc.ds.SETI")]
    public enum Target : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Planet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Life = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alien = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.IAlarm", CallbackContract=typeof(org.tsu.famc.ds.SETI.Scout.Proxy.IAlarmCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IAlarm {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAlarm/Subscribe")]
        void Subscribe(org.tsu.famc.ds.SETI.Scout.Proxy.Target target);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAlarm/Subscribe")]
        System.Threading.Tasks.Task SubscribeAsync(org.tsu.famc.ds.SETI.Scout.Proxy.Target target);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlarmCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAlarm/Alarm")]
        void Alarm(int[] data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlarmChannel : org.tsu.famc.ds.SETI.Scout.Proxy.IAlarm, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlarmClient : System.ServiceModel.DuplexClientBase<org.tsu.famc.ds.SETI.Scout.Proxy.IAlarm>, org.tsu.famc.ds.SETI.Scout.Proxy.IAlarm {
        
        public AlarmClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AlarmClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AlarmClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Subscribe(org.tsu.famc.ds.SETI.Scout.Proxy.Target target) {
            base.Channel.Subscribe(target);
        }
        
        public System.Threading.Tasks.Task SubscribeAsync(org.tsu.famc.ds.SETI.Scout.Proxy.Target target) {
            return base.Channel.SubscribeAsync(target);
        }
    }
}
