//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.tsu.famc.ds.SETI.Telescope.Proxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.IReceiver")]
    public interface IReceiver {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiver/Receive", ReplyAction="http://tempuri.org/IReceiver/ReceiveResponse")]
        void Receive(int[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiver/Receive", ReplyAction="http://tempuri.org/IReceiver/ReceiveResponse")]
        System.Threading.Tasks.Task ReceiveAsync(int[] data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReceiverChannel : org.tsu.famc.ds.SETI.Telescope.Proxy.IReceiver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceiverClient : System.ServiceModel.ClientBase<org.tsu.famc.ds.SETI.Telescope.Proxy.IReceiver>, org.tsu.famc.ds.SETI.Telescope.Proxy.IReceiver {
        
        public ReceiverClient() {
        }
        
        public ReceiverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceiverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Receive(int[] data) {
            base.Channel.Receive(data);
        }
        
        public System.Threading.Tasks.Task ReceiveAsync(int[] data) {
            return base.Channel.ReceiveAsync(data);
        }
    }
}
